version: '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      MYSQL_USER: "mysql_dev"
      MYSQL_PASSWORD: "mysql_d3v"
      MYSQL_DATABASE:       "eagle_eye_dev"
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  licensingservice:
     image: johncarnell/tmx-licensing-service:chapter3
     ports:
       - "8080:8080"
     environment:
       PROFILE: "dev"
       CONFIGSERVER_URI: "http://configserver:8888"
       CONFIGSERVER_PORT:   "8888"
       DATABASESERVER_PORT: "3306"
       ENCRYPT_KEY:       "IMSYMMETRIC"
