version: '2'
services:
  eurekaserver:
    image: johncarnell/tmx-eurekasvr:chapter5
    ports:
      - "8761:8761"
  configserver:
    image: johncarnell/tmx-confsvr:chapter5
    ports:
       - "8888:8888"
    environment:
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8761"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  zipkin:
    image: johncarnell/tmx-zipkinsvr:chapter5
    ports:
      - "9411:9411"
    environment:
      SERVER_PORT: "9411"
  zuulserver:
    image: johncarnell/tmx-zuulsvr:chapter5
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ZIPKIN_URI: "http://zipkin:9411"
      EUREKASERVER_PORT:        "8761"
      DATABASESERVER_PORT:      "3306"
      CONFIGSERVER_PORT:        "8888"
      ZIPKIN_PORT:         "9411"
  database:
    image: mysql:8.0.17
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "pjosif"
      MYSQL_PASSWORD: "josif.159"
      MYSQL_DATABASE:       "eagle_eye_local"
  licensingservice:
    image: johncarnell/tmx-licensing-service:chapter5
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
      AUTHSERVER_PORT:   "8091"
      ZIPKIN_URI: "http://zipkin:9411"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      DATABASESERVER_PORT: "3306"
      ZIPKIN_PORT:         "9411"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  organizationservice:
    image: johncarnell/tmx-organization-service:chapter5
    ports:
        - "8081:8081"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8081"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT:   "8761"
      AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
      AUTHSERVER_PORT:   "8091"
      ZIPKIN_URI: "http://zipkin:9411"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      DATABASESERVER_PORT: "3306"
      ZIPKIN_PORT:         "9411"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  authenticationservice:
      image: johncarnell/tmx-authentication-service:chapter5
      ports:
        - "8901:8901"
      environment:
        PROFILE: "default"
        SERVER_PORT: "8901"
        DATABASE_PORT:     "3306"
        CONFIGSERVER_PORT: "8888"
        EUREKASERVER_PORT: "8761"
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
        ENCRYPT_KEY:       "IMSYMMETRIC"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  kafkaserver:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
  logspout:
    image: gliderlabs/logspout
    command: syslog://logs5.papertrailapp.com:39755
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
