server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/Pjosif/microExm/
          searchPaths: licensingservice,organizationservice,zuulservice,authenticationservice
          username: pjosif
          password: Josif159

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
