version:  '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      MYSQL_USER: "mysql_prod"
      MYSQL_PASSWORD:  "mysql_pr0d"
      MYSQL_DATABASE: "eagle_eye_prod"
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  licensingservice:
      image: johncarnell/tmx-licensing-service:chapter3
      ports:
        - "8080:8080"
      environment:
        PROFILE: "prod"
        CONFIGSERVER_URI: "http://configserver:8888"
        CONFIGSERVER_PORT:   "8888"
        DATABASESERVER_PORT: "3306"
        ENCRYPT_KEY:       "IMSYMMETRIC"
